baseURL = 'https://m4rek.net/'
languageCode = 'en-us'
title = 'm4rek'
theme = 'lugo'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
